money:
  name: $
  storage-file: money.yml
  starting-balance: 0
essence:
  enabled: true
  provider: PlayerPoints
  name: Essence
commands:
  force-shop-hook: true
buy:
  min-price: 1
  max-price: 1000000
  max-items: 500
  default-sort: NEWEST
sell:
  allow-hand: true
  allow-all: true
auction:
  min-price: 1
  max-price: 1000000
  max-listings-per-player: 25
  confirm-purchase: true
  default-sort: NEWEST
orders:
  min-unit-price: 1
  max-unit-price: 1000000
  max-amount: 3456
  max-orders-per-player: 25
  default-sort: NEWEST
tools:
  pickaxe:
    enabled: true
    max-extra-blocks: 8
  axe:
    enabled: true
    max-logs: 128
  sellwand:
    enabled: true
